name: 🐛 Bug
description: Report an issue to help improve the project.
title: '[BUG] <description>'
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description:
        A brief description of the question or issue, also include what you tried and what didn't work. Please add screenshots if applicable along with steps to reproduce the issue. If you need help or if you want to to discuss something with us, join the WalkingPal [discord server community](https://discord.gg/Et3aQTsW6a)!
    validations:
      required: true
